GRAMS = 'grams'
CALS = 'cals'
AMOUNT = 'amount'
PROTEIN = 'protein'
CARBS = 'carbs'
FAT = 'fat'
WATER = 'water'
FOOD_NAME = 'food'
SALT = 'salt'
FIBER = 'fiber'
GLYCEMIC_INDEX = 'glycemic index'
QUALITY = 'quality'
REG = 'register'
ALIASES = 'aliases'

ORDERED_FIELDS = [FOOD_NAME, AMOUNT, GRAMS, CALS, PROTEIN, CARBS, FAT, WATER, SALT, FIBER, GLYCEMIC_INDEX, QUALITY, REG]
VISIBLE_FIELDS = [FOOD_NAME, GRAMS, CALS, PROTEIN, CARBS, FAT]
AGGREGABLE_FIELDS = [GRAMS, CALS, PROTEIN, CARBS, FAT, WATER, SALT, FIBER]

FILE = 'file'
WEEK = 'week'
DAY_NAME = 'day_name'
WEIGHT = 'weight'
MEAL_NUM = 'meal_num'

ORDERED_NO_FIELDS_COLUMNS = [FILE, WEEK, DAY_NAME, WEIGHT, MEAL_NUM]
READABLE_COLUMNS = ORDERED_NO_FIELDS_COLUMNS + ORDERED_FIELDS
VISIBLE_COLUMNS = [WEEK, DAY_NAME, WEIGHT] + VISIBLE_FIELDS
