
MICROSECONDS_IN_SECOND = 10**6
SECONDS_IN_HOUR = 3600
SECONDS_IN_MINUTE = 60
MINUTES_IN_HOUR = SECONDS_IN_HOUR / SECONDS_IN_MINUTE

FILE = 'file'
WEEK = 'week'
DAY_NAME = 'day_name'
WEIGHT = 'weight'
MEAL_NUM = 'meal_num'
FIELD_KEY = 'field_key'
FIELD_VALUE = 'field_value'

COLS_ORDER = [FILE, WEEK, DAY_NAME, WEIGHT, MEAL_NUM]
